/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentregister;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.time.LocalDate;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.namespace.QName;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.FactoryConfigurationError;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/**
 *
 * @author ndm3324
 */
public class StudentDisplayGUI extends javax.swing.JFrame {

    StudentInfoSet infoSet;
    StudentInfo selectedStudent;
    StudentInfo newStudent;
    private Document document;
    private static final String JAXP_SCHEMA_LANGUAGE
            = "http://java.sun.com/xml/jaxp/properties/schemaLanguage";
    private static final String W3C_XML_SCHEMA
            = "http://www.w3.org/2001/XMLSchema";
    private int index;
    javax.swing.JButton showPapersButton = new javax.swing.JButton();
    javax.swing.JButton removeStudentButton = new javax.swing.JButton();

    /**
     * Creates new form StudentDisplayGUI
     */
    public StudentDisplayGUI() {
        infoSet = new StudentInfoSet();
        selectedStudent = new StudentInfo("");
//        infoSet.addStudent(new StudentInfo("100010", "William", "Xu", LocalDate.of(1991, 04, 06), 'M'));
//        infoSet.addStudent(new StudentInfo("2000"));
//        infoSet.addStudent(new StudentInfo(""));
        initComponents();

        removeStudentButton.setText("Remove Student");
        removeStudentButton.setLocation(311, 407);
        removeStudentButton.setSize(113, 28);
        removeStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String id = studentList.getModel().getElementAt(index);
                infoSet.removeStudent(id);
                updateList();
            }
        });

        showPapersButton.setText("Show Papers");
        showPapersButton.setLocation(442, 407);
        showPapersButton.setSize(109, 28);
        showPapersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papersLable.setText(getStudentPapers());
                paperInfoFrame.setVisible(true);
            }
        });
        ((javax.swing.JPanel) jSplitPane1.getRightComponent()).add(showPapersButton);
//        ((javax.swing.JPanel)jSplitPane1.getRightComponent()).add(removeStudentButton);
        setLocationRelativeTo(null);
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paperInfoFrame = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        papersLable = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        addStudentFrame = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        addStudentIDLabel = new javax.swing.JLabel();
        addStudentID = new javax.swing.JTextField();
        addStudent = new javax.swing.JButton();
        addPaperFrame = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        addStudentIDLabel2 = new javax.swing.JLabel();
        addStudentID2 = new javax.swing.JTextField();
        addStudent2 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JList<String>(infoSet.getStudentKeys().toArray(new String[0]));
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenuBar = new javax.swing.JMenu();
        loadFileMenu = new javax.swing.JMenuItem();
        saveFileMenu = new javax.swing.JMenuItem();
        editMenuBar = new javax.swing.JMenu();
        addStudentMenu = new javax.swing.JMenuItem();
        addPaperMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        updateListMenu = new javax.swing.JMenuItem();

        paperInfoFrame.setTitle("Enrolled Papers");
        paperInfoFrame.setLocationByPlatform(true);
        paperInfoFrame.setMinimumSize(new java.awt.Dimension(100, 100));
        paperInfoFrame.setPreferredSize(new java.awt.Dimension(400, 300));
        paperInfoFrame.setResizable(false);
        paperInfoFrame.setSize(new java.awt.Dimension(400, 300));

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 50));

        papersLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        papersLable.setText(getStudentPapers());
        papersLable.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        papersLable.setMaximumSize(new java.awt.Dimension(300, 300));
        papersLable.setPreferredSize(new java.awt.Dimension(100, 100));

        confirmButton.setText("OK");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(papersLable, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(confirmButton)))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(papersLable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout paperInfoFrameLayout = new javax.swing.GroupLayout(paperInfoFrame.getContentPane());
        paperInfoFrame.getContentPane().setLayout(paperInfoFrameLayout);
        paperInfoFrameLayout.setHorizontalGroup(
            paperInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paperInfoFrameLayout.setVerticalGroup(
            paperInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );

        addStudentFrame.setLocationByPlatform(true);
        addStudentFrame.setMinimumSize(new java.awt.Dimension(100, 200));
        addStudentFrame.setResizable(false);
        addStudentFrame.setSize(new java.awt.Dimension(346, 121));
        addStudentFrame.setType(java.awt.Window.Type.POPUP);

        addStudentIDLabel.setText("Student ID:");

        addStudent.setText("Add Student");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(addStudentIDLabel)
                .addGap(29, 29, 29)
                .addComponent(addStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addStudent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentIDLabel)
                    .addComponent(addStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(addStudent)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addStudentFrameLayout = new javax.swing.GroupLayout(addStudentFrame.getContentPane());
        addStudentFrame.getContentPane().setLayout(addStudentFrameLayout);
        addStudentFrameLayout.setHorizontalGroup(
            addStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addStudentFrameLayout.setVerticalGroup(
            addStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addPaperFrame.setLocationByPlatform(true);
        addPaperFrame.setMinimumSize(new java.awt.Dimension(100, 200));
        addPaperFrame.setResizable(false);
        addPaperFrame.setSize(new java.awt.Dimension(346, 121));
        addPaperFrame.setType(java.awt.Window.Type.POPUP);

        addStudentIDLabel2.setText("Student ID:");

        addStudent2.setText("Add Student");
        addStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudent2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addStudentIDLabel2)
                .addGap(29, 29, 29)
                .addComponent(addStudentID2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );

        javax.swing.GroupLayout addPaperFrameLayout = new javax.swing.GroupLayout(addPaperFrame.getContentPane());
        addPaperFrame.getContentPane().setLayout(addPaperFrameLayout);
        addPaperFrameLayout.setHorizontalGroup(
            addPaperFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        addPaperFrameLayout.setVerticalGroup(
            addPaperFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(775, 530));
        setResizable(false);

        selectedStudentInfo = selectedStudent.getStudentPanel(false);
        jSplitPane1.setOpaque(false);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 23));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 100));

        studentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                studentListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(studentList);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(selectedStudent.getStudentPanel(false));

        FileMenuBar.setText("File");

        loadFileMenu.setText("Load file");
        loadFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuActionPerformed(evt);
            }
        });
        FileMenuBar.add(loadFileMenu);

        saveFileMenu.setText("Save File");
        saveFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileMenuActionPerformed(evt);
            }
        });
        FileMenuBar.add(saveFileMenu);

        jMenuBar1.add(FileMenuBar);

        editMenuBar.setText("Edit");

        addStudentMenu.setText("Add Student");
        addStudentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentMenuActionPerformed(evt);
            }
        });
        editMenuBar.add(addStudentMenu);

        addPaperMenu.setText("Add Paper");
        addPaperMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaperMenuActionPerformed(evt);
            }
        });
        editMenuBar.add(addPaperMenu);
        editMenuBar.add(jSeparator2);

        updateListMenu.setText("Update List");
        updateListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateListMenuActionPerformed(evt);
            }
        });
        editMenuBar.add(updateListMenu);

        jMenuBar1.add(editMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_studentListValueChanged

        selectedStudent = infoSet.getStudent(studentList.getSelectedValue());
        if (studentList.getSelectedIndex() > -1) {
            index = studentList.getSelectedIndex();

        }
        if (studentList.getSelectedValue() != null && selectedStudent != null) {
            setRightPane();
        }

        selectedStudent = infoSet.getStudent(studentList.getModel().getElementAt(index));
        updateList();
        ((javax.swing.JPanel) jSplitPane1.getRightComponent()).add(showPapersButton);
        ((javax.swing.JPanel) jSplitPane1.getRightComponent()).add(removeStudentButton);

    }//GEN-LAST:event_studentListValueChanged

    private void loadFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileMenuActionPerformed
        JFileChooser chooser = new JFileChooser(new File("."));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML", "xml");
        chooser.setFileFilter(filter);
        int status = chooser.showOpenDialog(this);
        if (status == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = chooser.getSelectedFile();
            FileInputStream fis = null;
            try {
                fis = new FileInputStream(fileToOpen);
                if (fis == null) {
                    document = null;
                } else {
                    try {
                        DocumentBuilderFactory builderFactory
                                = DocumentBuilderFactory.newInstance();
                        builderFactory.setNamespaceAware(true);
                        builderFactory.setValidating(true);
                        builderFactory.setAttribute(JAXP_SCHEMA_LANGUAGE,
                                W3C_XML_SCHEMA);
                        DocumentBuilder builder
                                = builderFactory.newDocumentBuilder();
                        // parse the input stream
                        document = builder.parse(fis);
                        document.getDocumentElement().normalize();
                        infoSet.loadStudentsFromXML(document);
                    } catch (FactoryConfigurationError | ParserConfigurationException | SAXException | IOException e) {
                    }
                }

                fis.close();
                updateList();
            } catch (IOException ioe) {
                System.out.println("IO exception:" + ioe);
            }
        }
    }//GEN-LAST:event_loadFileMenuActionPerformed

    /**
     * Includes auto setting of .xml extention when saving
     *
     * @param evt
     */
    private void saveFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileMenuActionPerformed
        JFileChooser chooser = new JFileChooser(new File("."));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("xml", "xml");
        chooser.setFileFilter(filter);
        int status = chooser.showSaveDialog(this);
        if (status == JFileChooser.APPROVE_OPTION) {
            File fileToSave = chooser.getSelectedFile();
            String path = fileToSave.toString();
            path += ".xml";
            fileToSave = new File(path);
            try {
                FileOutputStream fos = new FileOutputStream(fileToSave);
                JAXBSaver(fos);
                fos.close();
            } catch (IOException ioe) {
                System.out.println("IO exception:" + ioe);
            } catch (JAXBException ex) {
                System.out.println("JAXB exception: " + ex);
            }

        }
    }//GEN-LAST:event_saveFileMenuActionPerformed

    private void addStudentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentMenuActionPerformed
        addStudentFrame.setVisible(true);
    }//GEN-LAST:event_addStudentMenuActionPerformed

    private void updateListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateListMenuActionPerformed
        updateList();
    }//GEN-LAST:event_updateListMenuActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        paperInfoFrame.setVisible(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        newStudent = new StudentInfo(addStudentID.getText());
        infoSet.addStudent(newStudent);
        addStudentID.setText("");
        addStudentFrame.setVisible(false);
        updateList();
    }//GEN-LAST:event_addStudentActionPerformed

    private void addPaperMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaperMenuActionPerformed
        addPaperFrame.setVisible(true);
    }//GEN-LAST:event_addPaperMenuActionPerformed

    private void addStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudent2ActionPerformed
        selectedStudent.addPaper(addStudentID2.getText());
        addStudentID2.setText("");
        addPaperFrame.setVisible(false);
    }//GEN-LAST:event_addStudent2ActionPerformed

    private String getStudentPapers() {
        String papers = new String();

        if (selectedStudent != null && !selectedStudent.getEnrolledPapers().isEmpty()) {
            papers = "<html>";
            for (String p : selectedStudent.getEnrolledPapers()) {
                papers += p + "<br>";
            }
            papers += "</html>";
        } else {
            papers = "No papers found!";
        }

        return papers;
    }

    /**
     * Generation of xml is done using JAXB This was created using help from xjc
     * generated java classes in generated directory Information of this
     * technique was from Mohamed Sanaulla on javacodegeeks
     * https://www.javacodegeeks.com/2011/02/jaxb-generate-xml-xsd.html.
     *
     * @param os
     * @throws JAXBException
     */
    public void JAXBSaver(OutputStream os) throws JAXBException {
        Iterator<StudentInfo> i = infoSet.iterator();
        generated.ObjectFactory factory = new generated.ObjectFactory();
        generated.Students students = factory.createStudents();
        students.setDescription(infoSet.getDescription());
        StudentInfo next;
        while (i.hasNext()) {
            next = i.next();
            generated.StudentType student = factory.createStudentType();
            student.setFirstname(next.getFirstName());
            student.setLastname(next.getLastName());
            student.setStudentID(next.getStudentID());
            student.setGender(Character.toString(next.getGender()));
            student.setPictureURL(next.getPictureFileName());
            student.getPaper().addAll(next.getEnrolledPapers());
            generated.StudentType.Birthday birthday = factory.createStudentTypeBirthday();
            birthday.setDay(Integer.toString(next.getBirthDate().getDayOfMonth()));
            birthday.setMonth(Integer.toString(next.getBirthDate().getMonthValue()));
            birthday.setYear(Integer.toString(next.getBirthDate().getYear()));
            student.setBirthday(birthday);
            students.getStudent().add(student);
        }

        JAXBContext context = JAXBContext.newInstance("generated");
        JAXBElement<generated.Students> element = new JAXBElement<>(new QName("", "students"), generated.Students.class, null, students);
        Marshaller marshaller = context.createMarshaller();
        marshaller.setProperty("jaxb.formatted.output", Boolean.TRUE);
        marshaller.setProperty(Marshaller.JAXB_NO_NAMESPACE_SCHEMA_LOCATION, "students.xsd");
        marshaller.marshal(element, os);

    }

    private void updateList() {
        DefaultListModel model = new DefaultListModel();
        for (String key : infoSet.getStudentKeys()) {
            model.addElement(key);
        }
        studentList.setModel(model);
    }

    private void setRightPane() {
        jSplitPane1.setRightComponent(selectedStudent.getStudentPanel(false));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDisplayGUI().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenuBar;
    private javax.swing.JFrame addPaperFrame;
    private javax.swing.JMenuItem addPaperMenu;
    private javax.swing.JButton addStudent;
    private javax.swing.JButton addStudent2;
    private javax.swing.JFrame addStudentFrame;
    private javax.swing.JTextField addStudentID;
    private javax.swing.JTextField addStudentID2;
    private javax.swing.JLabel addStudentIDLabel;
    private javax.swing.JLabel addStudentIDLabel2;
    private javax.swing.JMenuItem addStudentMenu;
    private javax.swing.JButton confirmButton;
    private javax.swing.JMenu editMenuBar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private JPanel selectedStudentInfo;
    private javax.swing.JMenuItem loadFileMenu;
    private javax.swing.JFrame paperInfoFrame;
    private javax.swing.JLabel papersLable;
    private javax.swing.JMenuItem saveFileMenu;
    private javax.swing.JList<String> studentList;
    private javax.swing.JMenuItem updateListMenu;
    // End of variables declaration//GEN-END:variables

}
